#ifndef ALGOMODELCLASSES_GLOBAL_H
#define ALGOMODELCLASSES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ALGOMODELCLASSES_LIBRARY)
#  define ALGOMODELCLASSESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ALGOMODELCLASSESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ALGOMODELCLASSES_GLOBAL_H
